---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd

name: itrue-jellyfin
summary:  "Jellyfin: The Free Software Media System"
description: |
  Jellyfin is the volunteer-built media solution that puts you in control of
  your media. Stream to any device from your own server, with no strings
  attached. Your media, your server, your way.

  ---

  This is a community-developed snap and not officially supported or released
  by Jellyfin.
base: core22
confinement: strict
adopt-info: jellyfin
license: GPL-2.0
architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

package-repositories:
  - type: apt
    url: https://repo.jellyfin.org/ubuntu
    suites: [jammy]
    components: [main]
    key-id: 4918AABC486CA052358D778D49023CD01DE21A7B
    architectures:
      - arm64
      - armhf
      - amd64

parts:
  jellyfin:
    plugin: nil
    stage-packages:
      - jellyfin-server:${CRAFT_TARGET_ARCH}
      - jellyfin-web:all
      - jellyfin-ffmpeg6:${CRAFT_TARGET_ARCH}
      - va-driver-all:${CRAFT_TARGET_ARCH}
      - libavcodec58:${CRAFT_TARGET_ARCH}
      - libavcodec-extra58:${CRAFT_TARGET_ARCH}
      - vainfo:${CRAFT_TARGET_ARCH}
      - libdrm-common:${CRAFT_TARGET_ARCH}
      - on amd64:
        - intel-opencl-icd:${CRAFT_TARGET_ARCH}
    override-build: |
      craftctl default
      craftctl set grade="stable"
      craftctl set version="$(apt info jellyfin-server | grep -E "^Version:" | cut -f2 -d\ )"
    prime:
      - -usr/share/man
      - -var/spool
      # This library is unused and links against another library which doesn't exist in 22.04
      - -usr/lib/jellyfin/bin/libcoreclrtraceptprovider.so

apps:
  itrue-jellyfin:
    command: usr/lib/jellyfin/bin/jellyfin --ffmpeg $SNAP/usr/lib/jellyfin-ffmpeg/ffmpeg --restartpath $SNAP/usr/lib/jellyfin/restart.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - home
      - opengl
      - removable-media
      - mount-observe
      - firewall-control
    environment:
      JELLYFIN_LOG_DIR: "${SNAP_DATA}/logs"
      JELLYFIN_CACHE_DIR: "${SNAP_COMMON}/cache"
      JELLYFIN_CONFIG_DIR: "${SNAP_COMMON}/config"
      JELLYFIN_DATA_DIR: "${SNAP_COMMON}/data"
      JELLYFIN_WEB_DIR: "${SNAP}/usr/share/jellyfin/web"
  vainfo:
    command: usr/bin/vainfo
    plugs:
      - opengl
  ffmpeg:
    command: usr/lib/jellyfin-ffmpeg/ffmpeg
    plugs:
      - opengl

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio
  /usr/lib/$CRAFT_ARCH_TRIPLET/dri:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/dri
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/igfx_user_feature_next.txt:
    bind-file: $SNAP_DATA/igfx_user_feature_next.txt
  /etc/vdpau_wrapper.cfg:
    bind-file: $SNAP/etc/vdpau_wrapper.cfg
  /usr/lib/jellyfin-ffmpeg:
    bind: $SNAP/usr/lib/jellyfin-ffmpeg
  /etc/OpenCL:
    bind: $SNAP/etc/OpenCL
