---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd

name: itrue-jellyfin
summary:  "Jellyfin: The Free Software Media System"
description: |
  Jellyfin is the volunteer-built media solution that puts you in control of
  your media. Stream to any device from your own server, with no strings
  attached. Your media, your server, your way.

  ---

  This is a community-developed snap and not officially supported or released
  by Jellyfin.
base: core24
confinement: strict
adopt-info: jellyfin
license: GPL-2.0
platforms:
  amd64:
    build-on:
      - amd64
    build-for:
      - amd64
  arm64: 
    build-on:
      - arm64
    build-for:
      - arm64
source-code: https://github.com/IsaacJT/jellyfin-snap/tree/main
contact: isaac@is.having.coffee
issues: https://github.com/IsaacJT/jellyfin-snap/issues

package-repositories:
  - type: apt
    url: https://repo.jellyfin.org/ubuntu
    suites: [noble]
    components: [main]
    key-id: 4918AABC486CA052358D778D49023CD01DE21A7B
    architectures:
      - arm64
      - amd64

parts:
  jellyfin:
    plugin: nil
    stage-packages:
      - jellyfin-server:${CRAFT_ARCH_BUILD_FOR}
      - jellyfin-web:all
      - jellyfin-ffmpeg7:${CRAFT_ARCH_BUILD_FOR}
      - va-driver-all:${CRAFT_ARCH_BUILD_FOR}
      - libavcodec60:${CRAFT_ARCH_BUILD_FOR}
      - libavcodec-extra60:${CRAFT_ARCH_BUILD_FOR}
      - vainfo:${CRAFT_ARCH_BUILD_FOR}
      - libdrm-common:${CRAFT_ARCH_BUILD_FOR}
      - clinfo:${CRAFT_ARCH_BUILD_FOR}
      - on amd64:
        - intel-opencl-icd:${CRAFT_ARCH_BUILD_FOR}
        - libquadmath0:${CRAFT_ARCH_BUILD_FOR}
    override-build: |
      craftctl default
      craftctl set grade="stable"
      craftctl set version="$(apt info jellyfin-server | grep -E "^Version:" | cut -f2 -d\ )"
    prime:
      - -usr/share/man
      - -var/spool
      # This library is unused and links against another library which doesn't exist in 22.04
      - -usr/lib/jellyfin/bin/libcoreclrtraceptprovider.so

  scripts:
    plugin: nil
    source: scripts
    build-packages:
      - shellcheck
    override-build: |
      shellcheck "${CRAFT_PART_BUILD}"/*.sh
      install -Dm0755 "${CRAFT_PART_BUILD}"/*.sh \
        -t "${CRAFT_PART_INSTALL}"/usr/local/bin

apps:
  vainfo:
    command: usr/bin/vainfo
    plugs:
      - opengl
    environment: &_environment
      LD_LIBRARY_PATH: /usr/lib/jellyfin-ffmpeg/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/vdpau:$LD_LIBRARY_PATH
      LIBGL_DRIVERS_PATH: /usr/lib/jellyfin-ffmpeg/lib:/usr/lib/jellyfin-ffmpeg/lib/dri:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:$LIBGL_DRIVERS_PATH
      LIBVA_DRIVERS_PATH: /usr/lib/jellyfin-ffmpeg/lib:/usr/lib/jellyfin-ffmpeg/lib/dri:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:$LIBVA_DRIVERS_PATH
  ffmpeg:
    command: usr/lib/jellyfin-ffmpeg/ffmpeg
    plugs:
      - opengl
    environment: *_environment
  clinfo:
    command: usr/bin/clinfo
    environment: *_environment
    plugs:
      - opengl
  itrue-jellyfin:
    command: usr/local/bin/jellyfin.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - home
      - opengl
      - removable-media
      - mount-observe
      - firewall-control
    environment:
      <<: *_environment
      JELLYFIN_LOG_DIR: "${SNAP_DATA}/logs"
      JELLYFIN_CACHE_DIR: "${SNAP_COMMON}/cache"
      JELLYFIN_CONFIG_DIR: "${SNAP_COMMON}/config"
      JELLYFIN_DATA_DIR: "${SNAP_COMMON}/data"
      JELLYFIN_WEB_DIR: "${SNAP}/usr/share/jellyfin/web"

environment:
  # Enable OpenCL on older AMD cards
  ROC_ENABLE_PRE_VEGA: "1"

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri
  /usr/share/zoneinfo-icu:
    bind: $SNAP/usr/share/zoneinfo-icu
  /usr/share/libdrm/amdgpu.ids:
    bind-file: $SNAP/usr/share/libdrm/amdgpu.ids
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/igfx_user_feature_next.txt:
    bind-file: $SNAP_DATA/igfx_user_feature_next.txt
  /etc/vdpau_wrapper.cfg:
    bind-file: $SNAP/etc/vdpau_wrapper.cfg
  /usr/lib/jellyfin-ffmpeg:
    bind: $SNAP/usr/lib/jellyfin-ffmpeg
  /etc/OpenCL:
    bind: $SNAP/etc/OpenCL
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl
  /opt:
    bind: $SNAP/opt
