---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd

name: itrue-jellyfin
summary:  "Jellyfin: The Free Software Media System"
description: |
  Jellyfin is the volunteer-built media solution that puts you in control of
  your media. Stream to any device from your own server, with no strings
  attached. Your media, your server, your way.

  ---

  This is a community-developed snap and not officially supported or released
  by Jellyfin.
base: core22
confinement: strict
grade: stable
version: "10.8.9"
license: GPL-2.0
architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64
compression: lzo

parts:
  jellyfin:
    plugin: nil
    source: https://repo.jellyfin.org/releases/server/linux/stable/combined/jellyfin_${SNAPCRAFT_PROJECT_VERSION}_${CRAFT_TARGET_ARCH}.tar.gz
    override-build: |
      craftctl default

      mkdir -p ${CRAFT_PART_INSTALL}/opt
      cp -r ${CRAFT_PART_BUILD}/jellyfin_$(craftctl get version) \
        ${CRAFT_PART_INSTALL}/opt/jellyfin
    stage-packages:
      - libcurl4
      - libfontconfig1
      - libfreetype6
      - libicu70
      - ffmpeg
      - freeglut3
      - libglu1-mesa
      - libpulse0
      - libva-glx2
      - liblapack3
      - libblas3
      - vainfo
      - mesa-va-drivers
    prime:
      - -usr/share/man
      # This library is unused and links against another library which doesn't exist in 22.04
      - -opt/jellyfin/libcoreclrtraceptprovider.so

apps:
  server:
    command: opt/jellyfin/jellyfin
    daemon: simple
    plugs:
      - network
      - network-bind
      - home
      - opengl
      - removable-media
      - mount-observe
    environment:
      JELLYFIN_LOG_DIR: "${SNAP_DATA}/logs"
      JELLYFIN_CACHE_DIR: "${SNAP_COMMON}/cache"
      JELLYFIN_CONFIG_DIR: "${SNAP_COMMON}/config"
      JELLYFIN_DATA_DIR: "${SNAP_COMMON}/data"
  vainfo:
    command: usr/bin/vainfo
    plugs:
      - opengl

# Mount some directories to fix the hard-coded paths
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio
  /usr/lib/$CRAFT_ARCH_TRIPLET/dri:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/dri
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
