---
# SPDX-License-Identifier: GPL-2.0-only
name: build-snap
"on":
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build snap on ${{ matrix.build-host.name }}
    runs-on: ${{ matrix.build-host.value }}
    strategy:
      matrix:
        build-host:
          - name: Ubuntu 26.04 arm64
            value: ubuntu-26.04-arm
          - name: Ubuntu 26.04 amd64
            value: ubuntu-26.04
    steps:
      # yamllint disable rule:line-length
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Diagnostics
        run: |
          echo "::group::snapcraft version"
          snapcraft version || true
          echo "::endgroup::"
          echo "::group::lxd/lxc version"
          lxc version || true
          echo "::endgroup::"
          echo "::group::disk space"
          df -h
          echo "::endgroup::"
      - uses: canonical/craft-actions/snapcraft/pack@acd2f2e61c7563b38ba89390ca0e910fa7d2784f # v0.1.1
        with:
          # Temporarily use the candidate channel until some hotfixes related to
          # arm64/armhf packaging repositories make their way into stable
          channel: 9.x/candidate
      - name: Upload snapcraft logs on failure
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        # yamllint enable rule:line-length
        with:
          name: snapcraft-log
          path: ~/.local/state/snapcraft/log/
          if-no-files-found: warn
          retention-days: 14
